name: common_github_search
description: Shared Code between AngularDart and Flutter
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.8
  http: ^1.0.0
  stream_transform: ^2.0.0

dev_dependencies:
  bloc_lint: ^0.3.0
  bloc_test: 10.0.0
  test: ^1.24.0
  mockito: ^5.4.0
  build_runner: ^2.4.0
